protocol_mapping:
  "*": refgenie

pipelines:
  refgenie:
    name: refgenie
    path: "refgenie build"
    arguments:
      "--genome": genome
      "--asset": asset
    optional_arguments:
      "--fasta": local_fa
      "--gencode-gtf": gencode_gtf
      "--gencode-gtf": local_gencode_gtf
      "--ensembl-gtf": local_ensembl_gtf
      "--gff": local_ensembl_rb
      
