protocol_mapping:
  "refgenie": wget

pipelines:
  wget:
    name: wget
    path: "wget"
    command_template: >
      {%- for itype in sample.input_type -%}
        {%- if itype == 'files' -%}
          {{ pipeline.path + ' -O ' + sample.destdir + '/file.' + sample.genome + '.' + sample.asset + ' ' + sample.input_value[loop.index0] }}; 
        {%- endif -%}
      {%- endfor -%}